name: Secrets and Environment Variable

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest


    steps:
       - name: Read a variable
         run: echo " My APP_ID value is ${{ vars.APP_ID }}"
     
       - name: Tell me a secrets !
         run: echo " My existing secrets is ${{ secrets.API_KEY }}"

       - name: Unset secret
         run: echo " My unkown secret is ${{ secrets.DOES_NOT_EXIST }}"
     
    

    

    
  
